---
language: c
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
addons:
  apt:
    update: true
    packages:
      - libgmp3-dev
      - cabal-install-3.0
      - ghc-8.6.5
    sources:
      - hvr-ghc

install:
  - export PATH=/opt/ghc/bin:$PATH
  - cabal update
  - cabal install dhall --overwrite-policy=always
  - cabal install dhall-json --overwrite-policy=always
  - export PATH=$HOME/.cabal/bin:$PATH

script:
  - cat hlint.dhall | dhall --explain
  - cat hlint.dhall | dhall-to-yaml
